# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Deploing to Netlify

on:
  push:
    branches: [ master ]
    paths: 
      'src/s1/**'
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run Jekyll  
      id: push_directory
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}      
      run: |
        cd site1 && bundle install && bundle exec jekyll build
        mv _site _site_tmp 
        #mkdir /_gen
        #cp -R _site _gen 
        git add site1/_site_tmp
        git commit -m 'generated dir'
 #   - name: Deploy
 #     run: |
 #       curl -X POST -d {} https://api.netlify.com/build_hooks/60d1ce1ba766361822f0c9d9

